[package]
name = "primitives"
version = "0.1.0"
authors = ["Lachezar Lechev <lachezar@adex.network>, Omidiora Samuel <sam@adex.network>"]
edition = "2018"

[features]


[dependencies]
# Futures
futures-preview = { version = "=0.3.0-alpha.16", features = ["compat", "io-compat"]}
# (De)Serialization
serde = { version = "^1.0", features = ['derive'] }
serde_json = "1.0"
serde-hex = "0.1.0"
toml = "0.5"
# Domain
num-bigint = { version = "0.2", features = ["serde"] }
chrono = { version = "0.4", features = ["serde"] }
time = "0.1.42"
hex = "0.3.2"
num = "0.2.0"
# Fixtures
fake = { version = "^1.3", features = ["chrono"] }
rand = { version = "^0.6" }
