[tasks.pre-test]

dependencies = ["services-up"]

[tasks.post-test]

dependencies = ["services-down"]

[tasks.test]
env = { "POSTGRES_DB" = "sentry_leader" }

[tasks.services-up]
script = "docker-compose -f ../docker-compose.ci.yml up -d postgres-leader && sleep 2"

[tasks.services-down]
script = "docker-compose -f ../docker-compose.ci.yml down"
