language: rust
rust:
  - nightly
cache: cargo
env:
  global:
    - CARGO_MAKE_RUN_CHECK_FORMAT="true"
    - CARGO_MAKE_RUN_CLIPPY="true"
matrix:
  fast_finish: true
script:
  - which cargo-make || cargo install cargo-make
  - cargo make ci-flow