language: rust
rust:
  - nightly-2019-05-08
cache: cargo
env:
  global:
    - CARGO_MAKE_RUN_CHECK_FORMAT="true"
    - CARGO_MAKE_RUN_CLIPPY="true"
matrix:
  fast_finish: true
install:
  - if [[ $(cargo list | grep -c make) == 0 ]]; then cargo install --debug cargo-make ; else echo "Cargo make already installed, continuing..."; fi
  - cargo make ci-flow