language: rust
rust:
  - nightly-2019-05-08
cache: cargo
env:
  global:
    - CARGO_MAKE_RUN_CHECK_FORMAT="true"
    - CARGO_MAKE_RUN_CLIPPY="true"
matrix:
  fast_finish: true
install:
  - cargo install --debug cargo-make
  - cargo make ci-flow