language: rust
rust:
  - stable
# add nodejs for ganche-cli
node_js: "12.12.0"
# Need to cache the whole `.cargo` directory to keep .crates.toml for
# cargo-update to work
cache:
  directories:
    - /home/travis/.cargo
# But don't cache the cargo registry
before_cache:
  - rm -rf /home/travis/.cargo/registry
env:
  global:
    - CARGO_MAKE_RUN_CHECK_FORMAT="true"
    - CARGO_MAKE_RUN_CLIPPY="true"
services:
  - redis-server
matrix:
  fast_finish: true
script:
  - which cargo-make || cargo install cargo-make
  - cargo make ci-flow