language: rust
# do not run any default scripts coming from `language: rust` (i.e. travis-ci)
script:
install:
# Also don't cache the cargo registry
before_cache:
  - rm -rf /home/travis/.cargo/registry
rust:
  - 1.48.0
os: linux
# add nodejs for ganche-cli
node_js: "12.12.0"
# Need to cache the whole `.cargo` directory to keep .crates.toml for
# cargo-update to work
cache:
  directories:
    - /home/travis/.cargo
env:
  global:
    - CARGO_MAKE_RUN_CHECK_FORMAT="true"
    - CARGO_MAKE_RUN_CLIPPY="true"

stages:
  - name: run all tests
  - name: release validator
    if: (tag IS present) AND (tag =~ ^validator-v)

jobs:
  fast_finish: true
  include:
    - stage: run all tests
      # @TODO: Maybe run a separate weekly job and use the cached cargo-make from there
      install:
        - which cargo-make || cargo install cargo-make
      script:
        - cargo make ci-flow
      services:
        - redis
    - stage: release validator
      # Disable the default Rust `install` & `script` from Travis
      install:
      script:
      before_deploy:
        - cargo build -p validator_worker --release --all-features --target x86_64-unknown-linux-gnu
        - cp target/x86_64-unknown-linux-gnu/release/validator_worker $TRAVIS_TAG
      deploy:
        provider: releases
        token: $GITHUB_API_TOKEN
        file: $TRAVIS_BUILD_DIR/$TRAVIS_TAG
        cleanup: false
        draft: true
        on:
          tags: true
          all_branches: true
        edge: true
