[workspace]

members = [
    "adapter",
    "primitives",
    "validator_worker",
    "sentry",
    "adview-manager",
]

[patch.crates-io]
slog-term = { git = "https://github.com/slog-rs/term", branch = "master"}