version: '3.8'

x-postgres-configuration: &postgres
  POSTGRES_USER: 'adex'
  POSTGRES_HOST: 'postgres'
  POSTGRES_PASSWORD: 'postgres'

x-base-sentry-configuration: &sentry
  ENV: development
  ADAPTER: 'dummy'

services:
  sentry-leader:
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile-sentry
    container_name: adex-sentry-leader
    ports:
      - "8005:8005"
    environment:
      <<: *sentry
      <<: *postgres
      PORT: 8005
      POSTGRES_DB: sentry_leader
      DUMMY_IDENTITY: 'ce07CbB7e054514D590a0262C93070D838bFBA2e'
      REDIS_URL: redis://redis:6379/0

  sentry-follower:
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile-sentry
    container_name: adex-sentry-follower
    ports:
      - "8006:8006"
    environment:
      <<: *sentry
      <<: *postgres
      PORT: 8006
      POSTGRES_DB: sentry_follower
      DUMMY_IDENTITY: 'c91763d7f14ac5c5ddfbcd012e0d2a61ab9bded3'
      REDIS_URL: redis://redis:6379/1

  postgres:
    image: postgres
    container_name: adex-postgres
    restart: always
    volumes:
      - ./scripts/postgres:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      <<: *postgres
      POSTGRES_MULTIPLE_DATABASES: sentry_leader,sentry_follower

  redis:
    image: redis
    container_name: adex-redis
    restart: always

  ganache:
    build: ./scripts/ethereum
    image: adex-ganache
    container_name: adex-ganache-cli
    ports:
      - "8545:8545"
