[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = "true"
CARGO_MAKE_CLIPPY_ARGS = "--all-features"

[tasks.dev-test-flow]
dependencies = [
    "format-flow",
    "clippy",
    "pre-build",
    "build",
    "post-build",
    "test-flow",
]