[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt"]

[tasks.check-format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--check"]

[tasks.check-clippy]
install_crate = "clippy"
command = "cargo"
args = ["clippy", "--all-targets", "--all-features", "--", "-D", "warnings"]

[tasks.check-quick]
dependencies = [
    "check-format",
    "check-clippy",
    "test",
]

[tasks.test]
dependencies = [
    "test-no-features",
    "test-all-features",
]

[tasks.test-all-features]
command = "cargo"
args = ["test", "--all", "--all-features"]

[tasks.test-no-features]
command = "cargo"
args = ["test", "--all"]

[tasks.check-all]
dependencies = [
    "clean",
    "check-format",
    "check-clippy",
    "test",
]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]

[tasks.clean-build]
dependencies = [
	"clean",
    "build",
    "test"
]
