[package]
name = "adview-manager"
version = "0.1.0"
authors = ["Lachezar Lechev <lachezar@adex.network>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
adex_primitives = {path = "../primitives", package = "primitives"}
num-bigint = { version = "0.2", features = ["serde"] }
serde =  {version = "^1.0", features = ['derive']}
chrono = "0.4"
