[package]
authors = ["Lachezar Lechev <lachezar@adex.network>"]
edition = "2018"
name = "adview-manager"
version = "0.1.0"

[dependencies]
adex_primitives = {path = "../primitives", package = "primitives"}
chrono = "0.4"
num-bigint = {version = "0.3", features = ["serde"]}
serde = {version = "^1.0", features = ['derive']}
serde_json = "^1.0"
