[package]
name = "sentry"
version = "0.1.0"
authors = ["Omidiora Samuel <sam@adex.network>"]
edition = "2018"

[dependencies]
# Futures
futures-preview = { version = "=0.3.0-alpha.19", features = ["compat"]}
# Primitives
primitives = {path = "../primitives", features = ["postgres"]}
adapter = { version = "0.1", path = "../adapter" }
chrono = { version = "0.4", features = ["serde"] }
hex = "0.3.2"
# CLI
clap = "2.33.0"
# Server
tokio = "0.2.0-alpha.6"
hyper = {version = "=0.13.0-alpha.4", features = ["unstable-stream"]}
regex = "1"
# Database
redis = {version = "0.13.1-alpha.0", features = ["tokio-executor"]}
bb8 = {git = "https://github.com/djc/bb8", branch = "async-await"}
bb8-postgres = {git = "https://github.com/djc/bb8", branch = "async-await", features = ["with-chrono-0_4", "with-serde_json-1"]}
# Logger
slog = { version = "^2.2.3" , features = ["max_level_trace"] }
# Serde
serde = {version = "^1.0", features = ['derive']}
serde_json = "^1.0"
serde_urlencoded = "0.6.1"
# Other
lazy_static = "1.4.0"
