[package]
name = "sentry"
version = "0.1.0"
authors = ["Lachezar Lechev <lachezar@adex.network>"]
edition = "2018"

[lib]
name = "sentry"
path = "src/lib.rs"

[dependencies]
futures-preview = { version = "=0.3.0-alpha.13", features = ["compat", "io-compat"] }
futures_legacy = { version = "0.1", package = "futures" }
tokio = { version = "0.1", features = ["async-await-preview"] }
num-bigint = { version = "0.2", features = ["serde"] }
regex = "1"
hyper = "0.12"
hyper-tls = "0.3"
serde = "^1.0"
serde_derive = "1.0"
serde_json = "1.0"
postgres = "0.15"
