[package]
name = "sentry"
version = "0.1.0"
authors = ["Lachezar Lechev <lachezar@adex.network>"]
edition = "2018"

[lib]
name = "sentry"
path = "src/lib.rs"

[dependencies]
# Futures
futures-preview = { version = "=0.3.0-alpha.14", features = ["compat", "io-compat"] }
futures_legacy = { version = "0.1", package = "futures" }
# Concurrency
tokio = { version = "=0.1.19", features = ["async-await-preview"] }
# Database
tokio-postgres = { version = "=0.4.0-rc.2", features = ["with-chrono-0_4"] }
bb8 = "0.3.0"
bb8-postgres = "0.3.0"
# Server
regex = "1"
hyper = "0.12"
http = "0.1.16"
# (De)Serialization
serde = "^1.0"
serde_derive = "1.0"
serde_json = "1.0"
# Utils
try_future = "0.1.3"
# Domain
num-bigint = { version = "0.2", features = ["serde"] }
chrono = { version = "0.4", features = ["serde"] }