[tasks.test]
env = { "POSTGRES_DB" = "sentry_leader" }

[tasks.pre-test]

dependencies = ["services-up"]

[tasks.post-test]

dependencies = ["services-down"]

[tasks.services-up]
script = "docker-compose -f ../docker-compose.ci.yml up -d redis-leader postgres-leader && sleep 3"

[tasks.services-down]
script = "docker-compose -f ../docker-compose.ci.yml down"
