# Maximum number of channels to return per request
MAX_CHANNELS = 512
# 
CHANNELS_FIND_LIMIT = 200
WAIT_TIME = 500

AGGR_THROTTLE = 0
EVENTS_FIND_LIMIT = 100
MSGS_FIND_LIMIT = 10

HEARTBEAT_TIME = 30000
HEALTH_THRESHOLD_PROMILLES = 950
PROPAGATION_TIMEOUT = 1000

LIST_TIMEOUT = 5000
FETCH_TIMEOUT = 5000
VALIDATOR_TICK_TIMEOUT = 5000

[ratelimit]
IP_RATE_LIMIT = { type = "ip", timeframe = 20000 }
SID_RATE_LIMIT = { type = 'sid', timeframe = 20000 }

[ethereum]
ETHEREUM_CORE_ADDR = '0x333420fc6a897356e69b62417cd17ff012177d2b'
ETHEREUM_NETWORK = 'goerli'