# Maximum number of channels to return per request
max_channels = 512

channels_find_limit = 512
wait_time = 500

aggr_throttle = 5000
events_find_limit = 100
msgs_find_limit = 10

heartbeat_time = 60000
health_threshold_promilles = 970
propagation_timeout = 3000

list_timeout = 10000
fetch_timeout = 10000
validator_tick_timeout = 10000

ip_rate_limit = { type = "ip", timeframe = 20000 }

ethereum_core_address = '0x333420fc6a897356e69b62417cd17ff012177d2b'
ethereum_network = 'homestead'
token_address_whitelist = ['0x89d24A6b4CcB1B6fAA2625fE562bDD9a23260359']

creators_whitelist = []
minimal_deposit = 0
minimal_fee = 0
validators_whitelist = []