[package]
name = "adapter"
version = "0.1.0"
authors = ["Lachezar Lechev <lachezar@adex.network>"]
edition = "2018"

[features]
# Allows you to use a Dummy implementation of the Adapter for testing purposes
dummy-adapter = []

[dependencies]
domain = {path = "../domain"}
[dev-dependencies]
domain = {path = "../domain", features = ["fixtures"]}
