[package]
name = "adapter"
version = "0.1.0"
authors = ["Lachezar Lechev <lachezar@adex.network>, Omidiora Samuel <sam@adex.network>"]
edition = "2018"

[dependencies]
primitives = { path = "../primitives" }
# Time handling
chrono = "0.4"
# To/From Hex
hex = "0.4"
serde = { version = "^1.0", features = ['derive'] }
serde_json = "1.0"
serde-hex = "0.1.0"
# Ethereum
web3 = { version = "0.15", features = ["http-tls", "signing"] }
eth_checksum = "0.1"
tiny-keccak = "1.5"
ethstore = { git = "https://github.com/openethereum/openethereum", tag = "v3.1.1-rc.1" }
ethabi = "13.0.0"

# API client
reqwest = { version = "0.11", features = ["json"] }
# reqwest = { version = "0.10", features = ["json"] }

sha2 = "0.8.0"
base64 = "0.10.1"
lazy_static = "^1.4"
# Futures
futures = { version = "0.3", features = ["compat"] }
async-trait = "0.1"
tokio-compat-02 = "0.2"

[dev-dependencies]
byteorder = "^1.4"
# tokio 0.2 is required since `web3` is still on this version
# tokio = { version = "0.2", features = ["macros", "rt-threaded"] }
tokio = { version = "^1", features = ["macros", "rt-multi-thread"] }
wiremock = "0.4"
