[package]
name = "adapter"
version = "0.1.0"
authors = ["Lachezar Lechev <lachezar@adex.network>, Omidiora Samuel <sam@adex.network>"]
edition = "2018"

[features]
# Allows you to use a Dummy implementation of the Adapter for testing purposes
dummy-adapter = ["serde", "hex"]

[dependencies]
primitives = {path = "../primitives"}
# Futures
futures-preview = {version = "=0.3.0-alpha.16"}
# Time handling
chrono = "0.4"
time = "0.1.42"
# To/From Hex
hex = {version = "0.3.2", optional = true}
serde =  {version = "^1.0", features = ['derive'], optional = true}
# Ethereum
web3 = { git = "https://github.com/tomusdrw/rust-web3" }
eth_checksum = "0.1.1"

[dev-dependencies]
primitives = {path = "../primitives", features = ["fixtures"]}
