[package]
name = "adapter"
version = "0.1.0"
authors = ["Lachezar Lechev <lachezar@adex.network>"]
edition = "2018"

[features]
# Allows you to use a Dummy implementation of the Adapter for testing purposes
dummy-adapter = ["serde", "hex"]

[dependencies]
domain = {path = "../domain"}
# Futures
futures-preview = {version = "=0.3.0-alpha.16"}
# Time handling
chrono = "0.4"
time = "0.1.42"
# To/From Hex
hex = {version = "0.3.2", optional = true}
serde =  {version = "^1.0", features = ['derive'], optional = true}
[dev-dependencies]
domain = {path = "../domain", features = ["fixtures"]}
