[package]
name = "adapter"
version = "0.1.0"
authors = ["Lachezar Lechev <lachezar@adex.network>, Omidiora Samuel <sam@adex.network>"]
edition = "2018"

[dependencies]
primitives = {path = "../primitives"}
# Time handling
chrono = "0.4"
# To/From Hex
hex = "0.3.2"
serde =  {version = "^1.0", features = ['derive']}
serde_json = "1.0"
serde-hex = "0.1.0"
# Ethereum
web3 = { git = "https://github.com/samparsky/rust-web3", features=['http', 'ipc', 'ws'] }
eth_checksum = "0.1.1"
ethabi = { git = "https://github.com/samparsky/ethabi", branch = "graph-patches" }
tiny-keccak = "1.5"
parity-crypto = { version = "0.4.2", features = ["publickey"], git = "https://github.com/paritytech/parity-common" }
ethstore = { version = "0.2.1", git = "https://github.com/paritytech/parity-ethereum"}
ethkey = { version = "0.4.0", git = "https://github.com/paritytech/parity-ethereum"}
sha2 = "0.8.0"
base64 = "0.10.1"
lazy_static = "1.4.0"

[dev-dependencies]
byteorder = "1.3"