[tasks.dev-test-flow]
description = "Development testing flow will first format the code, and than run cargo build and test"
category = "Development"
dependencies = [
  "format-flow",
  "format-toml-conditioned-flow",
  "pre-build",
  "build",
  "post-build",
  "ganache-start",
  "test-flow",
  "ganache-stop",
]

[tasks.ganache-start]
script = { file = "scripts/start-docker.sh" }

[tasks.ganache-stop]
script = { file = "scripts/stop-docker.sh" }
