[tasks.pre-test]

dependencies = ["ganache-up"]

[tasks.post-test]

dependencies = ["ganache-down"]

[tasks.ganache-up]
script = '''
docker-compose -f ../docker-compose.ci.yml up -d ganache \
&& sleep 10
'''

[tasks.ganache-down]
script = "docker-compose -f ../docker-compose.ci.yml down"
